# Generated by Django 2.0.8 on 2018-09-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('RTR', 'Router'), ('SW', 'Switch'), ('SFP', 'SFP'), ('CB', 'Cable')], default='RTR', max_length=100)),
                ('item_model', models.CharField(max_length=1000)),
                ('item_quantity', models.IntegerField()),
                ('item_status', models.CharField(choices=[('RTR', 'Router'), ('SW', 'Switch'), ('SFP', 'SFP'), ('CB', 'Cable')], default='ST', max_length=1000)),
            ],
        ),
    ]
