# Generated by Django 2.1.1 on 2019-03-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20180925_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='item_status',
            field=models.CharField(choices=[('PROJECT', 'Project'), ('STOCK', 'Stock')], default='STOCK', max_length=1000),
        ),
        migrations.AlterField(
            model_name='store',
            name='item_type',
            field=models.CharField(choices=[('RTR', 'Router'), ('FW', 'Firewall'), ('SW', 'Switch'), ('SFP', 'SFP'), ('CABLE', 'Cable')], default='RTR', max_length=100),
        ),
    ]
