# Generated by Django 2.0.8 on 2018-09-18 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tasks_assingee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='assingee',
            new_name='assignee',
        ),
    ]
