---
core:
    num_workers: 100
logging:
    file: "/home/wamer/netops/automation/nornir.log"
inventory:
    plugin: nornir.plugins.inventory.netbox.NBInventory
    options:
        nb_url: "http://172.20.22.99"
        nb_token: "49d66235f10e0d388f18e179e756d1d276b898bb"
